FROM nvcr.io/nvidia/deepstream:7.0-triton-multiarch

# Update and install dependencies
RUN apt update && apt install -y python3-gi python3-dev python3-gst-1.0 python-gi-dev git meson \
    python3 python3-pip python3.10-dev cmake g++ build-essential libglib2.0-dev \
    libglib2.0-dev-bin libgstreamer1.0-dev libtool m4 autoconf automake \
    libgirepository1.0-dev libcairo2-dev

RUN apt update && apt-get install --reinstall gstreamer1.0-alsa \
    gstreamer1.0-plugins-base gstreamer1.0-pulseaudio \
    libgstreamer-plugins-bad1.0-0 libgstreamer-plugins-base1.0-0 libgstreamer-plugins-good1.0-0 libgstreamer1.0-0 -y

RUN apt install \
    libssl3 \
    libssl-dev \
    libgles2-mesa-dev \
    libgstreamer1.0-0 \
    gstreamer1.0-tools \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-libav \
    libgstreamer-plugins-base1.0-dev \
    libgstrtspserver-1.0-0 \
    libjansson4 \
    libyaml-cpp-dev \
    libjsoncpp-dev \
    protobuf-compiler \
    gcc \
    make \
    git \
    python3 -y
# Show working directory and list files
RUN pwd && ls -la && echo "Building from directory: $(pwd)"

# Clone the deepstream_python_apps repository and initialize submodule in the same RUN command
RUN cd sources && git clone https://github.com/NVIDIA-AI-IOT/deepstream_python_apps.git && \
    cd deepstream_python_apps && \
    echo "Cloned repository and moved into deepstream_python_apps"

RUN cd /opt/nvidia/deepstream/deepstream/sources/deepstream_python_apps/ && \
    git submodule update --init && \
    echo "Initialized submodule"

# Install additional certificates and perform upgrades
RUN apt-get install -y apt-transport-https ca-certificates
RUN update-ca-certificates

# Update and upgrade system packages
RUN apt update && apt upgrade -y

# Install python-gi-dev
RUN apt install -y python-gi-dev

RUN apt update

# Navigate to gst-python directory, run Meson and Ninja build
RUN cd /opt/nvidia/deepstream/deepstream/sources/deepstream_python_apps/3rdparty/gstreamer/subprojects/gst-python/ && \
    meson build && \
    meson configure && \
    cd build && \
    ninja && \
    ninja install

# Build DeepStream Python bindings
RUN cd /opt/nvidia/deepstream/deepstream/sources/deepstream_python_apps/bindings/ && \ 
    mkdir build && \
    cd build && \
    cmake ..  -DPYTHON_MAJOR_VERSION=3 -DPYTHON_MINOR_VERSION=10 \
        -DPIP_PLATFORM=linux_x86_64 -DDS_PATH=/opt/nvidia/deepstream/deepstream/ && \
    make

RUN cd /opt/nvidia/deepstream/deepstream/sources/deepstream_python_apps/bindings/build && \ 
    python3 -m pip install --upgrade pip && \
    pip3 install ./pyds*.whl && \
    pip3 install cuda-python
